[project]
name = "agriculture"
authors = [
    { name = "Frappe", email = "pandikunta@frappe.io" }
]
description = "Agriculture management for ERPNext"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
license = { text = "MIT" }

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "agriculture"
